### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by DaniDelHoyo**
Protocol test

### CODE REVIEW

**Comment by mmmtnez** [comment]
Error:

When running scipion3 tests esm.tests.test_conplex
the next error appears:

Scipion v3.0.13 - Eugenius
Running tests....
module_name:  esm.tests.test_conplex
module_name:  esm.tests
module_name:  esm
[   FAILED ] _FailedTest.esm


Traceback (most recent call last):
  File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: esm
Traceback (most recent call last):
  File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/loader.py", line 155, in loadTestsFromName
    module = __import__(module_name)
  File "/home/marta/software/plugins/scipion-em-esm/esm/__init__.py", line 37, in <module>
    from scipion.install.funcs import InstallHelper
ImportError: cannot import name 'InstallHelper' from 'scipion.install.funcs' (/home/marta/software/plugins/scipion-app/scipion/install/funcs.py)



[==========] run 1 tests (0.001 secs)

[  FAILED  ] 1 tests

[  PASSED  ] 0 tests

**Comment by DaniDelHoyo** [comment]
> Error:
> 
> When running scipion3 tests esm.tests.test_conplex the next error appears:
> 
> Scipion v3.0.13 - Eugenius Running tests.... module_name: esm.tests.test_conplex module_name: esm.tests module_name: esm [ FAILED ] _FailedTest.esm
> 
> Traceback (most recent call last): File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor yield File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run self._callTestMethod(testMethod) File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod method() File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/loader.py", line 34, in testFailure raise self._exception ImportError: Failed to import test module: esm Traceback (most recent call last): File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/loader.py", line 155, in loadTestsFromName module = **import**(module_name) File "/home/marta/software/plugins/scipion-em-esm/esm/**init**.py", line 37, in from scipion.install.funcs import InstallHelper ImportError: cannot import name 'InstallHelper' from 'scipion.install.funcs' (/home/marta/software/plugins/scipion-app/scipion/install/funcs.py)
> 
> [==========] run 1 tests (0.001 secs)
> 
> [ FAILED ] 1 tests
> 
> [ PASSED ] 0 tests

Hi Marta, the error comes from an old version of scipion-app. If you update it (either on devel or master), the error should dissapear.

**Comment by mmmtnez** [comment]
Thank you Dani, after updating scipion-em, scipion-pyworflow and scipion-app I have tried to run the same command:

           scipion3 tests esm.tests.test_conplex

This time the first answer was:
          Are you missing mrcfile ? Are you in devel mode ?. So, please run: scipion3 pip install mrcfile
Then I have installed that y run the previous command again. this answer time was:

Scipion v3.3.0 - Eugenius
Running tests....
module_name:  esm.tests.test_conplex
module_name:  esm.tests
module_name:  esm
[   FAILED ] _FailedTest.esm


Traceback (most recent call last):
  File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: esm
Traceback (most recent call last):
  File "/home/marta/software/miniconda/envs/scipion3/lib/python3.8/unittest/loader.py", line 155, in loadTestsFromName
    module = __import__(module_name)
  File "/home/marta/software/plugins/scipion-em-esm/esm/__init__.py", line 37, in <module>
    from scipion.install.funcs import InstallHelper
  File "/home/marta/software/plugins/scipion-app/scipion/install/__init__.py", line 28, in <module>
    from .funcs import Environment
  File "/home/marta/software/plugins/scipion-app/scipion/install/funcs.py", line 42, in <module>
    from typing_extensions import Self
ModuleNotFoundError: No module named 'typing_extensions'



[==========] run 1 tests (0.001 secs)

[  FAILED  ] 1 tests

[  PASSED  ] 0 tests

**Comment by mmmtnez** [comment]
I have another question: Why the test is called test_conplex and also test_esmfold? (same error in both cases)

**Comment by mmmtnez** [comment]
Hi Dani,

Remove .idea and scipion_em_esm.egg-info folders because .idea is unnecessary (it stores the configuration of your editor) and scipion_em_esm.egg-info gives information of the local instalation in your machhine.

Modify installation process to install CUDA 11-3 when installing Pytorch 11.3 (try to install everything you need, all the dependencies)

**Review by mmmtnez — APPROVED** [review]

**Pull request merged**
